name: to_do_list
description: "To-do list App"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  go_router: ^13.0.1
  shimmer: ^3.0.0
  provider: ^6.1.1
  intl: ^0.19.0
  timer_builder: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

assets:
  - assets/

fonts:
  - family: pretendard
    fonts:
      - asset: assets/fonts/Pretendard-Black.ttf
      - asset: assets/fonts/Pretendard-Bold.ttf
      - asset: assets/fonts/Pretendard-ExtraBold.ttf
      - asset: assets/fonts/Pretendard-ExtraLight.ttf
      - asset: assets/fonts/Pretendard-Light.ttf
      - asset: assets/fonts/Pretendard-Mediujm.ttf
      - asset: assets/fonts/Pretendard-Regular.ttf
      - asset: assets/fonts/Pretendard-SemiBold.ttf
      - asset: assets/fonts/Pretendard-Thin.ttf